### ISSUE TITLE
`filter_single` on singleton object exclusive constraint vs property exclusive constraint

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb-js#690] opened 2023-07-14 19:16 UTC
**Code**

```typescript
e.select(e.X, x => ({
  filter_single: { field: params.field },
}))
```

**Schema**

Your application schema.

```edgeql
module default {
  type X {
    required property field: str;
    constraint exclusive on (.field);
  }
}
```

**Generated EdgeQL**

N/A, doesn't pass type checking

**Error or desired behavior**

```
Type error: Type '$expr_Select<{ __element__: ObjectType<"default::X", { id: PropertyDesc<$uuid, Cardinality.One, true, false, true, true>; **type**: LinkDesc<$ObjectType, ... 5 more ..., false>; .... }, Omit<...>, ExclusiveTuple>; __cardinality__: Cardinality.Many...' is not assignable to type 'TypeSet<ObjectType<string, { id: PropertyDesc<$uuid, Cardinality.One, true, false, true, true>; **type**: LinkDesc<$ObjectType, Cardinality.One, ... any, ExclusiveTuple>, Cardinality.AtMostOne | ... 1 more ... | Cardinality.Empty> | ...'.
...
Types of property '**cardinality**' are incompatible.
Type 'Cardinality.Many' is not assignable to type 'Cardinality.AtMostOne | Cardinality.One | Cardinality.Empty'.
```

This is unexpected since the `filter_single: { field: params.field },` syntax works in the following case where the constraint is on the field instead of on the object,
```esdl
required property field: str {
        constraint exclusive;
}
```

**_and_** works in the case where it is on the object instead of the field, but with multiple fields in the constraint

```esdl
module default {
  type X {
    required property x: str;
    required property y: str;

    constraint exclusive on ((.x, .y));
  }
}
```

```typescript
filter_single: { x: "x", y: "y" },
```

**Versions (please complete the following information):**

- OS: macos 13.1
- EdgeDB version (e.g. `2.0`): 3.1
- EdgeDB CLI version (e.g. `2.0`): 3.4.0+4d95a2c
- `edgedb-js` version (e.g. `0.20.10`;): 1.3.3
- `@edgedb/generate` version (e.g. `0.0.7`;): 0.3.1
- Typescript version: 5.1.6
- Node/Deno version: 16.16.0

**Comment by scotttrinh** [comment] 2023-07-14 19:23
Thanks @jackfischer ! Duplicate of #677 , so feel free to subscribe to that issue.

**Closed by scotttrinh** 2023-07-14 19:23 UTC
