### ISSUE TITLE
Allow overlapping keys in polymorphic queries

### ISSUE THREAD

**Issue by scotttrinh** [edgedb/edgedb-js#723] opened 2023-08-24 18:22 UTC
Currently if two subtypes contain the same keys, using the `e.is` function cannot generate the proper EdgeQL query.

Example:

Schema:

```ruby
abstract type A {
  a: str;
}

type B extending A {
  b: int;
}

type C extending A {
  b: str;
}
```

EdgeQL:

```ruby
select A {
  a,
  [is B].b,
  [is C].b
}
```

Query Builder:

```ts
e.select(e.A, () => ({
  a: true,
  ...e.is(e.B, { b: true }),
  ...e.is(e.C, { b: true }),
}));
```

In the Query Builder case, you end up overriding the `e.B` property with `e.C` rather than having both of them end up in the final query data structure.

**Comment by jaclarke** [comment] 2023-08-24 19:27
Duplicate of #630

**Closed** 2023-08-24 19:31 UTC
Labels: bug
