### ISSUE TITLE
Generating queries for Typescript (`--target ts`) results in import error/conflict

### ISSUE THREAD

**Issue by tjjfv** [edgedb/edgedb-js#540] opened 2023-02-13 16:14 UTC
When generating query functions for Typescript (`npx @edgedb/generate queries --target ts`), an EdgeQL file `<path>/<name>.edgeql` results in a TS file `<path>/<name>.edgeql.ts` (as expected per [the docs](https://www.edgedb.com/docs/clients/js/generation#:~:text=queries%3A%20Scans%20your%20project%20for%20*.edgeql%20files%20and%20generates%20a%20file%20containing%20a%20strongly%2Dtyped%20function%20alongside%20each.).

However, to `import` the TS file it must be specified as `.../<name>.edgeql` (since by default[^1] the filename must not include a `.ts` extension) and that results in 'importing' from the EdgeQL file at `.../<name>.edgeql`, which results in an error.

[^1]: Overriding the default currently requires using the 5.0 beta with a [new compiler option](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#allowimportingtsextensions) that restricts other common compiler configurations.

**Comment by tjjfv** [comment] 2023-02-13 16:26
Having the generated files under a different extension (`*.eql.ts` or `*.e.ts`[^1]) is likely to be the only viable solution for avoiding the conflict.

The generator should do this by default so that it works without additional configuration by every user.

[^1]: Personally, my preference is `*.e.ts`.

**Comment by scotttrinh** [comment] 2023-05-01 15:48
Confirmed the issue here. The `--file` option doesn't suffer from this, so here are some additional fixes here:

1. Remove the in-place conversion and just generate a single file, similar to how the other two generators work.
2. Remove the `edgeql` infix so that `<name>.edgeql` becomes `<name>.ts`
   - I consider the proposed solution here to be a bit of a variation that allows you to configure how that replacement works, but I think we can/should standardize on how we do this to eliminate confusion and lower the maintenance burden for documentation.

---

Of those 2.5 solutions, I'm personally leaning toward the first solution since it's the most congruent with the other generators, has the least number of edge cases, and is the simplest thing to implement. It _is_ a breaking change though, so I definitely want to hear from folks who use the `queries` generator about what the advantages of having separate modules/files for each query are.

**Comment by scotttrinh** [comment] 2023-05-02 01:23
Found this little note from @1st1 about preferring the co-located, inline generation: https://github.com/edgedb/edgedb-js/issues/314#issuecomment-1148114305

> Hm, this would make my preferred project organization painful. I like using things like css modules and keeping related css/backend/frontend pieces close. I'd hate if the system forces me to have only globally unique query names. So i'm -1 on this.

**Comment by rcoedo** [comment] 2023-05-02 09:44
Nice points @scotttrinh!

> 1. Remove the in-place conversion and just generate a single file, similar to how the other two generators work.

I also lean towards this solution. My main point against the `--file` option is having generated code polluting the `src` folder. 

Instead of our current solutions, I like how [prisma handles the generated code for a schema](https://www.prisma.io/docs/concepts/components/prisma-client#2-installation). You install `@prisma/client` and [it generates the code in its own node_modules folder](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#the-prismaclient-npm-package). 

> Hm, this would make my preferred project organization painful. I like using things like css modules and keeping related css/backend/frontend pieces close. I'd hate if the system forces me to have only globally unique query names. So i'm -1 on this.

I also think this is a valid point, especially for code bases that are structured using a DDD approach. For this case I think we could have an API to generate code dynamically. I'm thinking of something like this:

```ts
// defines one query function
export const getUserById = client.defineQuery(`
    SELECT User { id, email, firstName, lastName }
    FILTER .id = <uuid>$id
`);
```

Some other maybe less straight-forward options:

```ts
// defines one query function from an `edgeql` file
export const getUserByEmail = client.defineQuery("./get-user-by-email.edgeql");

// defines an object that holds the queries found by the match expression.
export const user = client.defineQuery("./**/user/*.edgeql");
``` 

What I like about this API is that we have non generated code that we can structure as we please. The drawback is it impacts the application performance bootstrap time. We would need to check how much of a problem it is.

Regarding performance, I've noticed that the generator connects to the database to read the required metadata to generate the types. We could use the prisma approach and generate schema metadata into the `node_modules` folder on install, then use that intermediate schema to build the queries dynamically. This would make it fast enough to dynamically define the queries when bootstrapping the application.

**Comment by rcoedo** [comment] 2023-05-02 09:51
For anyone still dealing with this problem, here's TS script to rename all the generated files:

```ts
import * as fs from "fs";
import * as path from "path";

function renameEdgeqlFiles(dir: string): void {
  const files = fs.readdirSync(dir);

  files.forEach((file) => {
    const filePath = path.join(dir, file);
    const fileStat = fs.statSync(filePath);

    if (fileStat.isDirectory()) {
      renameEdgeqlFiles(filePath);
    } else if (path.extname(file) === ".ts" && file.endsWith(".edgeql.ts")) {
      const newFileName = file.replace(".edgeql.ts", ".query.ts");
      const newPath = path.join(dir, newFileName);
      fs.renameSync(filePath, newPath);
      console.log(`Renamed: ${filePath} -> ${newPath}`);
    }
  });
}

const args = process.argv.slice(2);
const startDir = args[0] || "./";

renameEdgeqlFiles(startDir);
```

Here's also the npm script that I was using to generate files: 
```
npx @edgedb/generate queries --force-overwrite && ts-node ./dbschema/rename-queries.ts ./src
```

**Comment by scotttrinh** [comment] 2023-05-02 15:53
@rcoedo 

> My main point against the --file option is having generated code polluting the src folder.

Maybe I'm misunderstanding this position, but all of the generators write specifically to the `dbschema` folder, including this one when using the `--file` approach without a value for the flag, which is [the example given in the docs](https://www.edgedb.com/docs/clients/js/queries#single-file-mode). But, even if you don't like it writing to `dbschema/queries.ts`, you can specify some other location if you'd like.

> I like how [prisma handles the generated code for a schema](https://www.prisma.io/docs/concepts/components/prisma-client#2-installation). You install @prisma/client and [it generates the code in its own node_modules folder](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#the-prismaclient-npm-package).

This is actually a great idea in general and solves the `.gitignore` dance we currently do since most (all?) JS consumers would already be ignoring this folder. We could possibly even have an import API like `import { getUserById } from "edgedb/generated/queries";` or something like that.

I'm digging the direction here.

> I also think this is a valid point, especially for code bases that are structured using a DDD approach. For this case I think we could have an API to generate code dynamically. I'm thinking of something like this:

> use that intermediate schema to build the queries dynamically. This would make it fast enough to dynamically define the queries when bootstrapping the application.

I like the direction that this is going in, but I would still want static generation rather than runtime generation if only for the developer experience of getting more straightforward types. I agree that emitting and caching the metadata so that subsequent generations are faster could be something that we explore to speed up generation runs, but caching introduces it's own complexities so I'd rather avoid it for now while trying to solve this more specific question.

---

In general, I think there are a few different things we can improve here based on the discussion so far:

1. Developer experience of generating and using all three generators (consistency, sane defaults)
2. Support for inline query generator files

For 1, I think defaulting to a single file and moving the generated files into `/node_modules` for all the generators would be an improvement and would require a breaking change in the `@edgedb/generate` package. We can spin off this part into a separate RFC/Discussion, so for now, let's address getting inline importing working within this issue:

I have two proposals:
1. Change the generated file name to be `<name>.query.ts` and specifically do _not_ allow configuration:
    ```ts
    import { getUserById } from "./getUserById.query";
    ```
2. Combine all queries in a directory into a single `queries.ts` file:
    ```ts
    import { getUserById, getUserByEmail } from "./queries";
    ```

I'm leaning toward the second option since it seems like it's both consistent (--file creating a single `queries.ts` and default creating multiple `queries.ts`) and allows for co-location at the cost of squatting the `queries.ts` file name.

That file name squatting is a legitimate concern with the rise of file-name based frameworks like Next.js, so I think that's a legitimate concern. Trying to stay ahead of the frameworks by introducing our own special sigil feel brittle, so I don't think that's a reasonable solution. Certainly the first one is _also_ susceptible to some framework claiming that _any_ file within a directory has some potential conflict, but it seems more likely that the frameworks will continue to be more friendly toward unique names within a directory.

**Comment by scotttrinh** [comment] 2023-05-02 15:57
As an alternative to the node/ts script given by @rcoedo (many thanks for providing that snippet!), here's a one-liner shell script you can throw in your `package.json` scripts:

```sh
find . -name "*.edgeql.ts" -type f -exec sh -c 'mv "$0" "${0%.edgeql.ts}.query.ts"' {} \;
```

**Comment by scotttrinh** [comment] 2023-05-12 15:51
Had some good discussion with @jaclarke and @1st1 about this and here is our current plan:

## Fix side-by-side generation by changing the infix

My current pick is `getFoo.edgeql` -> `getFoo.query.ts`. This is will be my very next priority since it's currently broken, so expect a fix for this out in the next week or so.

## Switch to single-file generation as the default

I feel like this is both the most common flow for consumers, and also the one most consistent with the other generators. We do not have a planned timeline for this since it's a breaking, but we'll likely bundle that change up with some other breaking changes in a `1.0.0` release for the `@edgedb/generate` package. We plan to support having side-by-side generation even once we switch the default here.

**Closed** 2023-06-02 16:14 UTC
Labels: bug, help wanted
