### ISSUE TITLE
Support for double splat (`**`) in query builder

### ISSUE THREAD

**Issue by XAMPPRocky** [edgedb/edgedb-js#728] opened 2023-09-07 07:47 UTC
Currently you can only use the `*` operator if you want all of the properties, but this means that for links you have to specify them all manually for each link, and this can nested quite a bit with each link potentially having links to other types.

It would be nice if the query builder also supported `**`, so that it wouldn't require so much boilerplate.

**Comment by scotttrinh** [comment] 2023-09-07 12:28
Thanks for the report, this is a duplicate of https://github.com/edgedb/edgedb-js/issues/558. It's on my radar, but no timeline at the moment. You can get double-splat behavior with the queries builder in the meantime.

> each link potentially having links to other types.

Double-splat only provides one level of links as per https://www.edgedb.com/docs/edgeql/select#splats:

> Splats allow you to select all properties of a type using the asterisk (`*`) or all properties of the type and a single level of linked types with a double asterisk (`**`).

**Closed by scotttrinh** 2023-09-07 12:28 UTC
